 service: SERVICE-NAME
# plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: 'yarn'

package:
  include:
    - src/**
    - node_modules/**
  exclude:
    - .git/**
    - .env
    - docker-compose.yml
    - Dockerfile
    - LICENSE
    - README.md
    - package.json
    - package-lock.json
    - tests/**
    - yarn.lock

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-2
  environment: ${file(env.yml):${self:provider.stage}}

functions:
  ping:
    handler: handler.ping
    events:
      - http:
          path: ping
          method: get
          cors: true
           # authorizer:
